import type { Metadata } from "next";
import SiteNav from "@/components/SiteNav";
import SiteFooter from "@/components/SiteFooter";
import CTAButton from "@/components/CTAButton";

export const metadata: Metadata = {
  title: "About — Adam Sowden",
  description:
    "26 years of building businesses. One conclusion: the business that grows without the owner is the only business worth building.",
};

export default function AboutPage() {
  return (
    <>
      <SiteNav />
      <main className="flex-1">
        <Hero />
        <TheStory />
        <TheReclaim />
        <FinalCTA />
      </main>
      <SiteFooter />
    </>
  );
}

function Hero() {
  return (
    <section className="bg-white">
      <div className="mx-auto max-w-6xl px-6 pt-16 pb-14 md:pt-24 md:pb-20 grid md:grid-cols-[1fr_1fr] gap-12 md:gap-16 items-center">
        <div>
          <p className="text-[#188bf6] text-sm font-medium uppercase tracking-[0.18em] mb-6">
            About
          </p>
          <h1 className="font-serif text-5xl md:text-6xl tracking-tight leading-[1.05] text-[#111111]">
            Hi, I&apos;m Adam Sowden.
          </h1>
          <p className="mt-7 text-lg md:text-xl text-[#111111]/75 leading-relaxed">
            I spent 26 years building businesses the hard way. I now build
            them to run without me — and show other owners how to do the
            same, using AI as the architecture of the business, not as a
            tool to do more work faster.
          </p>
        </div>
        <div className="flex justify-center md:justify-end">
          <div className="w-64 h-64 md:w-80 md:h-80 rounded-full bg-[#F9FAFB] border border-black/5 flex items-center justify-center text-black/30 text-sm">
            [Adam&apos;s photo]
          </div>
        </div>
      </div>
    </section>
  );
}

function TheStory() {
  return (
    <section className="bg-[#F9FAFB]">
      <div className="mx-auto max-w-3xl px-6 py-24 md:py-32">
        <p className="text-xs uppercase tracking-[0.18em] text-[#188bf6] font-medium mb-4">
          The Story
        </p>
        <h2 className="font-serif text-4xl md:text-5xl tracking-tight leading-[1.1] text-[#111111]">
          The business that grows without you is the only business worth
          building.
        </h2>

        <div className="mt-10 space-y-6 text-lg text-[#111111]/80 leading-relaxed">
          <p>
            For 26 years I ran businesses the same way most owners do. I was
            the bottleneck for every decision, every campaign, every client
            delivery. The harder I pushed on growth, the more the business
            demanded from me. The trap tightened. Revenue was capped by the
            hours I could work. Time was capped by what the business
            required.
          </p>
          <p>
            When AI arrived, I watched business owners do the predictable
            thing. They used it to do the same work faster. They were more
            productive and more trapped simultaneously. I named this The Old
            Mindset. It is the one enemy. Every specific problem keeping
            owners stuck is a version of it.
          </p>
          <p>
            I built something different. A Content Ecosystem that produces
            the content, publishes it, distributes it, and converts it —
            without me. An embedded Participation Layer that turns every
            reader into a conversation. A suite of AI agents that execute
            cognitive work my team used to do, at a quality higher than a
            human practitioner could produce alone.
          </p>
          <p>
            I tested it on my own business first. Then I proved it with
            clients — financial advisors operating in one of the most
            heavily regulated markets in the world. The result was over
            $1 billion in client pipelines, generated by a system that
            runs while the advisor sleeps.
          </p>
        </div>
      </div>
    </section>
  );
}

function TheReclaim() {
  return (
    <section className="bg-white">
      <div className="mx-auto max-w-6xl px-6 py-24 md:py-32">
        <div className="grid md:grid-cols-[1fr_1.2fr] gap-12 md:gap-20 items-start">
          <div>
            <p className="text-xs uppercase tracking-[0.18em] text-[#188bf6] font-medium mb-4">
              The Proof
            </p>
            <h2 className="font-serif text-4xl md:text-5xl tracking-tight leading-[1.1] text-[#111111]">
              The 36-Hour Reclaim.
            </h2>
          </div>
          <div className="space-y-6 text-lg text-[#111111]/80 leading-relaxed">
            <p>
              By applying the Four-Filter Rule to my own business, I
              eliminated 36 hours a week of personal time dependency while
              revenue increased. The tasks removed: blog writing, email
              writing, ad copy, image creation, content posting, ad
              performance analysis.
            </p>
            <p>
              The system executes all of these without me. I did not hire
              a team to do them. I did not outsource them to an agency. I
              built the architecture. The business runs. I do something
              else.
            </p>
            <p className="text-[#111111] font-medium">
              That is the baseline. Anything less is still a job.
            </p>
          </div>
        </div>

        <div className="mt-16 grid sm:grid-cols-3 gap-8 border-t border-black/10 pt-12">
          <Stat value="26 yrs" label="building businesses" />
          <Stat value="$1B+" label="in client pipelines" />
          <Stat value="10x" label="lead quality improvement" />
        </div>
      </div>
    </section>
  );
}

function Stat({ value, label }: { value: string; label: string }) {
  return (
    <div>
      <div className="font-serif text-4xl md:text-5xl tracking-tight text-[#111111]">
        {value}
      </div>
      <div className="mt-2 text-sm text-black/60">{label}</div>
    </div>
  );
}

function FinalCTA() {
  return (
    <section className="bg-[#F9FAFB]">
      <div className="mx-auto max-w-4xl px-6 py-24 md:py-32 text-center">
        <h2 className="font-serif text-4xl md:text-5xl tracking-tight leading-[1.1] text-[#111111]">
          Want to see what this looks like for your business?
        </h2>
        <p className="mt-6 text-lg text-[#111111]/75 max-w-2xl mx-auto leading-relaxed">
          A 20-minute Quick Chat. No pitch. We look at where owner
          dependency is costing you growth and what becomes possible when
          it&apos;s removed.
        </p>
        <div className="mt-10 inline-flex">
          <CTAButton size="lg">Book a Quick Chat</CTAButton>
        </div>
      </div>
    </section>
  );
}
